### ISSUE TITLE
Add scroll to top button

### ISSUE THREAD

**Issue by nikhil-prabhu** [nikhil-prabhu/nikhil-prabhu.github.io#6]
Add a scroll to top button that appears on the bottom right of the screen when the page is scrolled down a bit.

**Comment by nikhil-prabhu** [comment]
I've added a button at the bottom right of the page that scrolls back to the top. @ahmedsuhailsa you can now add a script that hides and shows the button as required.

**Comment by ahmedsasuhail** [comment]
Script added!
